### ISSUE TITLE
Type checks fail in index.ts

### ISSUE THREAD

**Issue by NfNitLoop** [serh11p/noble-base58check#1]
When trying to use base58check in Deno, I get type errors when checking files which depend on this module.

```
PS C:\Users\Cody\code\deno-feed\rss2feoblog> deno run --unstable -A .\rss2fb.ts
Check file:///C:/Users/Cody/code/deno-feed/rss2feoblog/rss2fb.ts
error: TS2580 [ERROR]: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    } else if (typeof process === "object" && "node" in process.versions) {
                      ~~~~~~~
    at https://deno.land/x/base58check@v0.1.2/index.ts:201:23

TS2580 [ERROR]: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    } else if (typeof process === "object" && "node" in process.versions) {
                                                        ~~~~~~~
    at https://deno.land/x/base58check@v0.1.2/index.ts:201:57

TS2580 [ERROR]: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
      const { createHash } = require("crypto");
                             ~~~~~~~
    at https://deno.land/x/base58check@v0.1.2/index.ts:202:30

Found 3 errors.
```

That seems to be referring to this line:
<https://github.com/serh11p/noble-base58check/blob/92fbe11/index.ts#L201>

AFAICT, execution shouldn't actually get that far, since `typeof window == "object" && "crypto" in window` is true in Deno:

```
> deno --version
deno 1.11.3 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2

> deno
Deno 1.11.3
exit using ctrl+d or close()
> typeof window == "object" && "crypto" in window
true
```

So maybe this is just overzealous type checking?

**Comment by serg-plusplus** [comment]
I guess, I fixes this. Try `0.1.4` version.
Deno link: https://deno.land/x/base58check@v0.1.4

**Comment by NfNitLoop** [comment]
That works, thanks!

I'm curious, your change for e93639fe10887acb04d6ac94f02306ba35c524fd seems a lot more involved than #2. 

I see the benefit of only defining the Node versions of sha256 in index.js.  Would my PR have worked as well, or did it cause other issues?
